[version]
path = "src/ym2s/__about__.py"

[[envs.all.matrix]]
python = ["3.8", "3.9", "3.10", "3.11", "3.12"]

[envs.default]
dependencies = []

[envs.test]
dependencies = [
  "coverage[toml]",
  "mypy",
  "pyhamcrest",
  "pytest",
  "ruff",
]

[envs.test.scripts]
test-lint = "ruff check {args:src/ym2s tests}"
test-pytest = "pytest {args:tests}"
test-mypy = "mypy --config-file ./mypy.ini --install-types --non-interactive {args:src/ym2s tests}"
check = [
  "test-lint",
  "test-pytest",
  "test-mypy",
]

lint-format = "ruff format {args:src/ym2s tests}"
lint-fix = "ruff check --fix {args:src/ym2s tests}"
lint = [
  "lint-format",
  "lint-fix",
]

test-coverage = "coverage run -m pytest {args:tests}"
coverage-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "test-coverage",
  "coverage-report",
]
