[version]
path = "src/ym2s/__about__.py"

[[envs.all.matrix]]
python = ["3.8", "3.9", "3.10", "3.11", "3.12"]

[envs.default]
dependencies = []

[envs.lint]
skip-install = true
dependencies = [
  "ruff",
]

[envs.lint.scripts]
check = "ruff check {args:src/ym2s tests}"
fix = "ruff check --fix {args:src/ym2s tests}"
format = "ruff format {args:src/ym2s tests}"

[envs.test]
dependencies = [
  "coverage[toml]",
  "pytest",
  "pyhamcrest",
]

[envs.test.scripts]
test = "pytest {args:tests}"
test-cov = "coverage run -m pytest {args:tests}"
cov-report = [
  "- coverage combine",
  "coverage report",
]
cov = [
  "test-cov",
  "cov-report",
]

[envs.types]
dependencies = [
  "mypy>=1.0.0",
  "pyhamcrest",
]

[envs.types.scripts]
check = "mypy --config-file ./mypy.ini --install-types --non-interactive {args:src/ym2s tests}"
